blank_issues_enabled: true

contact_links:
  - name: ðŸ“š Documentation Request
    url: https://github.com/kannan-ravi/tms
    about: For documentation improvements, open a discussion or PR directly.
